#!/bin/bash

: ${DOCKER_USER:? required}

VERSION=$(cat chart/route-admissioner/Chart.yaml | grep -E '^appVersion: [0-9\.]+$' | tr -d 'appVersion: ')

dep ensure -v
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o route-admissioner ./cmd/admissioner
docker build --no-cache -t ${DOCKER_USER}/route-admissioner:${VERSION} .
docker tag ${DOCKER_USER}/route-admissioner:${VERSION} ${DOCKER_USER}/route-admissioner:latest
rm -rf route-admissioner

docker push ${DOCKER_USER}/route-admissioner:${VERSION}
docker push ${DOCKER_USER}/route-admissioner:latest