#!/bin/bash

: ${DOCKER_USER:? required}

VERSION=$(cat chart/route-admissioner/Chart.yaml | grep -E '^appVersion: .+$' | sed 's/^appVersion: //')

docker build -t ${DOCKER_USER}/route-admissioner:${VERSION} .

docker push ${DOCKER_USER}/route-admissioner:${VERSION}