kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: route-admissioner-cr
  namespace: {{ .Release.Namespace }}
  labels:
    app: route-admissioner
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - pods
      - events
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
  - verbs:
      - '*'
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - '*'
    apiGroups:
      - autoscaling
    resources:
      - '*'
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - '*'
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
      - certificatesigningrequests/status
      - certificatesigningrequests/approval
  - verbs:
      - '*'
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
