kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: route-admissioner-crb
  namespace: {{ .Release.Namespace }}
  labels:
    app: route-admissioner
subjects:
- kind: ServiceAccount
  name: route-admissioner
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: route-admissioner-cr