apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: route-admissioner
  namespace: {{ .Release.Namespace }}
  labels:
    app: route-admissioner
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    app: route-admissioner
  triggers:
    - type: ConfigChange 
  template:
    metadata:
      labels:
        app: route-admissioner
    spec:
    {{- if .Values.controller.nodeSelector }}
      nodeSelector: {{ toYaml .Values.controller.nodeSelector | nindent 8 }}
    {{- end }}
      serviceAccountName: route-admissioner
      initContainers:
        - name: admissioner-init
          image: {{ .Values.controller.image.repository }}:{{ $.Chart.AppVersion }}
          command: ['./init.sh']
          imagePullPolicy: IfNotPresent
        {{- if .Values.controller.resources }}
          resources: {{ toYaml .Values.controller.resources | nindent 12 }}
        {{- end }}
          env:
            - name: namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      containers:
        - name: route-admissioner
          image: {{ .Values.controller.image.repository }}:{{ $.Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
        {{- if .Values.controller.resources }}
          resources: {{ toYaml .Values.controller.resources | nindent 12 }}
        {{- end }}
          args:
            - -tlsCertFile=/etc/admissioner/certs/cert.pem
            - -tlsKeyFile=/etc/admissioner/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: admissioner-certs
              mountPath: /etc/admissioner/certs
              readOnly: true
      volumes:
        - name: admissioner-certs
          secret:
            secretName: route-admissioner-certs
    {{- if .Values.controller.affinity }}
      affinity: {{ toYaml .Values.controller.affinity | nindent 8 }}
    {{- end }}
