apiVersion: v1
kind: Service
metadata:
  name: route-admissioner-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: route-admissioner
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: route-admissioner